# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ApplicationRegisterService_pb2 as ApplicationRegisterService__pb2


class ApplicationRegisterServiceStub(object):
  """register service for ApplicationCode, this service is called when service starts.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/ApplicationRegisterService/register',
        request_serializer=ApplicationRegisterService__pb2.Application.SerializeToString,
        response_deserializer=ApplicationRegisterService__pb2.ApplicationMapping.FromString,
        )


class ApplicationRegisterServiceServicer(object):
  """register service for ApplicationCode, this service is called when service starts.
  """

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApplicationRegisterServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=ApplicationRegisterService__pb2.Application.FromString,
          response_serializer=ApplicationRegisterService__pb2.ApplicationMapping.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ApplicationRegisterService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
