# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyWithStringValue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KeyWithStringValue.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18KeyWithStringValue.proto\"0\n\x12KeyWithStringValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB$\n org.skywalking.apm.network.protoP\x01\x62\x06proto3')
)




_KEYWITHSTRINGVALUE = _descriptor.Descriptor(
  name='KeyWithStringValue',
  full_name='KeyWithStringValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyWithStringValue.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='KeyWithStringValue.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['KeyWithStringValue'] = _KEYWITHSTRINGVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyWithStringValue = _reflection.GeneratedProtocolMessageType('KeyWithStringValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYWITHSTRINGVALUE,
  __module__ = 'KeyWithStringValue_pb2'
  # @@protoc_insertion_point(class_scope:KeyWithStringValue)
  ))
_sym_db.RegisterMessage(KeyWithStringValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n org.skywalking.apm.network.protoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
