# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Downstream_pb2 as Downstream__pb2
import TraceSegmentService_pb2 as TraceSegmentService__pb2


class TraceSegmentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.collect = channel.stream_unary(
        '/TraceSegmentService/collect',
        request_serializer=TraceSegmentService__pb2.UpstreamSegment.SerializeToString,
        response_deserializer=Downstream__pb2.Downstream.FromString,
        )


class TraceSegmentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def collect(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TraceSegmentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'collect': grpc.stream_unary_rpc_method_handler(
          servicer.collect,
          request_deserializer=TraceSegmentService__pb2.UpstreamSegment.FromString,
          response_serializer=Downstream__pb2.Downstream.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TraceSegmentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
